import { Injectable, inject } from '@angular/core';
import { Observable, throwError } from 'rxjs';
import { catchError, map, switchMap } from 'rxjs/operators';
import { AiPayload, AiPayloadService, PackageFacts } from './ai-payload.service';
import {
  AiCompletionResponse,
  AiProviderService,
  AiError
} from './ai-provider.service';
import { AiCacheService } from './ai-cache.service';
import {
  PROS_CONS_JSON_SCHEMA,
  PROS_CONS_SCHEMA_VERSION,
  ProsConsResponse
} from './schemas/pros-cons.schema';

/**
 * Pros & Cons orchestrator. Glues together:
 *   1. AiPayloadService — fetches Bundlephobia, NPM downloads, GitHub
 *      metrics, release cadence, dependency profile, README for both
 *      packages.
 *   2. AiProviderService — sends the payload to the resolved AI back-end
 *      (Groq proxy by default, BYO Gemini/OpenAI/DeepSeek if configured).
 *   3. AiCacheService — handles BOTH cross-call persistence (24h–7d TTL
 *      in localStorage) AND in-flight dedup (single concurrent network
 *      call per cache key). The orchestrator no longer reimplements
 *      either — see the design notes in ai-cache.service.ts.
 *   4. Schema validation — guarantees the orchestrator's caller gets
 *      `ProsConsResponse` and never has to handle drift.
 *
 * # Cache invalidation surface
 *
 * The cache key includes `PROS_CONS_SCHEMA_VERSION` (from the schema
 * file) and `PROMPT_VERSION` (local constant below). Bumping either
 * invalidates every cached entry for this feature in a single ship —
 * we never serve stale output that doesn't match the current UI's
 * expectations.
 */
@Injectable({ providedIn: 'root' })
export class ProsConsService {
  private readonly payload = inject(AiPayloadService);
  private readonly ai = inject(AiProviderService);
  private readonly cache = inject(AiCacheService);

  /**
   * Generate a comparative analysis between `pkgA` and `pkgB`. Returns
   * the parsed, schema-validated response plus metadata about which
   * provider handled it (for the "AI-generated by Groq · 4.2s" footer).
   *
   * On cache hit, returns instantly with `fromCache: true`. On miss,
   * calls the AI provider, caches the result with a 7-day TTL, and
   * returns it. In-flight calls with the same key share one network
   * call automatically — handled inside the cache layer.
   *
   * @param forceRefresh true to bypass the cache read (still writes
   * the fresh result). Used by the panel's Refresh button when the
   * user wants newer output than the cache has.
   */
  generate(
    pkgA: string,
    pkgB: string,
    forceRefresh = false
  ): Observable<AiCompletionResponse<ProsConsResponse>> {
    return this.cache.getOrFetch<ProsConsResponse>({
      feature: 'pros-cons',
      pair: [pkgA, pkgB],
      provider: this.ai.activeProvider(),
      model: 'default', // we let AiProviderService pick the model per provider
      schemaVersion: PROS_CONS_SCHEMA_VERSION,
      promptVersion: PROMPT_VERSION,
      // 7 days. Pros & Cons leans on slow-moving metrics — bundle size,
      // weekly downloads, GitHub stars — that don't shift meaningfully
      // day-to-day. The Refresh button is the escape hatch.
      ttlMs: 7 * 24 * 60 * 60 * 1000,
      bypassCache: forceRefresh,
      factory: () =>
        this.payload.forPackages({ name: pkgA }, { name: pkgB }).pipe(
          switchMap((payload) => this.callModel(payload))
        )
    });
  }

  /**
   * Build the prompt payload and dispatch through `AiProviderService`.
   * The prompt is split into a stable system prompt (caching-friendly
   * if the provider offers prompt caching later) and a per-call user
   * prompt with the freshly-fetched facts.
   */
  private callModel(
    payload: AiPayload
  ): Observable<AiCompletionResponse<ProsConsResponse>> {
    if (!payload.packageA || !payload.packageB) {
      return throwError(
        () => new Error('Pros & Cons requires two packages.')
      );
    }
    return this.ai
      .complete<ProsConsResponse>({
        systemPrompt: SYSTEM_PROMPT,
        userPrompt: this.buildUserPrompt(payload),
        responseSchema: PROS_CONS_JSON_SCHEMA,
        // Pros & Cons is small — the schema caps each axis at ~150 chars
        // and we ask for 4-6 axes plus a verdict and 0-3 warnings. 1000
        // tokens is a comfortable cap with headroom.
        maxTokens: 1000,
        // Slightly higher than 0 so the recommendation reads like prose
        // not a robot, but still tight enough to keep claims grounded.
        temperature: 0.25
      })
      .pipe(
        // Sanity check on the verdict length — the schema doesn't enforce
        // a max chars rule (JSON Schema's maxLength is unevenly supported
        // across providers), so we trim defensively here.
        map((res) => {
          const data = { ...res.data };
          if (data.verdict.length > 220) {
            data.verdict = data.verdict.slice(0, 217).trimEnd() + '…';
          }
          return { ...res, data };
        }),
        catchError((err: AiError | Error) => throwError(() => err))
      );
  }

  /**
   * Compose the user prompt. Kept compact: facts are JSON-serialized so
   * the model can reference them by exact field name, with a single
   * leading line clarifying which package is which.
   */
  private buildUserPrompt(payload: AiPayload): string {
    const a = this.compactFacts(payload.packageA);
    const b = this.compactFacts(payload.packageB!);
    return [
      `Compare these two npm packages:`,
      ``,
      `## Package A: ${payload.packageA.name}`,
      '```json',
      JSON.stringify(a, null, 2),
      '```',
      ``,
      `## Package B: ${payload.packageB!.name}`,
      '```json',
      JSON.stringify(b, null, 2),
      '```',
      ``,
      `Generate a structured Pros & Cons comparison following the schema. Pick the 4-6 axes that actually matter for THIS comparison; skip axes where both are equivalent.`
    ].join('\n');
  }

  /**
   * Trim each PackageFacts to the fields the model actually reasons over,
   * dropping bulk fields (full README) the system prompt already covers.
   * Smaller payloads = faster generation + cheaper.
   */
  private compactFacts(facts: PackageFacts): Record<string, unknown> {
    return {
      name: facts.name,
      version: facts.version,
      description: facts.description,
      bundleSize: facts.bundleSize,
      downloads: facts.downloads,
      repo: facts.repo,
      releases: facts.releases,
      dependencies: facts.dependencies,
      majorVersionChurn: facts.majorVersionChurn,
      // Send a SHORT README excerpt — first 1500 chars only — so the
      // model gets a sense of positioning/voice without burning the
      // budget. The Usage Guide feature uses the full truncated README.
      readmeExcerpt: facts.readme
        ? facts.readme.truncated.slice(0, 1500)
        : null
    };
  }
}

// ---------------------------------------------------------------------------
// System prompt — versioned constant
// ---------------------------------------------------------------------------

/**
 * Bump this when SYSTEM_PROMPT below changes meaningfully. The cache
 * key includes this number, so a bump invalidates every cached
 * pros-cons response generated under the old prompt — users always
 * see output that matches our current expectations.
 */
const PROMPT_VERSION = 1;

/**
 * The system prompt is the longest-lived, highest-stakes piece of text
 * in this feature. It sets:
 *   - The model's role and audience.
 *   - Hard rules about evidence-grounding and not-inventing.
 *   - How to handle missing fact sources (acknowledge, don't guess).
 *   - The exact guidelines for axis selection and verdict shape.
 *
 * Kept as a top-level constant so changes are easy to diff across
 * commits when we tune behaviour.
 */
const SYSTEM_PROMPT = `\
You are a comparative-analysis writer for an Angular package compatibility tool. Developers use you to decide between two npm packages competing for the same job.

You receive objective fact-data about each package: bundle size, NPM downloads (with trend), GitHub metrics, release cadence, dependency profile, major-version churn, and a short README excerpt.

CRITICAL RULES — your output is rejected if you violate any of these:

1. EVIDENCE GROUNDING. Every claim in your output must be grounded in one of the provided fact sources. If something isn't in the data, do not say it. Never invent benchmarks, performance numbers, or feature lists.

2. README IS MARKETING, NOT EVIDENCE. The README excerpt is author-written and inherently biased. Use it only to identify each package's claimed positioning ("billed as a router replacement" / "promotes itself as zero-config"). Never cite it as evidence for factual claims about quality, performance, or adoption.

3. ACKNOWLEDGE GAPS. If a fact source is null/missing, state that explicitly in the relevant axis (e.g. "bundle size data unavailable") rather than skipping silently. Skipping a missing fact looks like an oversight; calling it out looks like rigour.

4. QUANTIFY DELTAS. Express comparative claims with numbers when possible: "12 KB smaller gzipped", "3.2x more weekly downloads", "released 4 majors in the last 12 months vs 1." Vague comparisons ("better performance", "more popular") are not acceptable unless you have no quantitative source.

5. PICK 4-6 AXES. The schema allows 6 axes; you don't have to use all of them. Pick the ones with a real story. Skip axes where both packages are equivalent or where you have no data — quality over completeness.

6. VERDICT IS A HEADLINE. The verdict field is one sentence, ≤ 200 chars, capturing the single most important difference. Not a summary, not a recommendation — just the headline a developer would screenshot.

7. RECOMMENDATION IS ACTIONABLE. The recommendation field synthesizes the axes into a decision: "pick A if you need X, pick B if you need Y." It must help a real developer making a real choice today, not generic platitudes.

8. WARNINGS ARE CONCRETE. Risk callouts about adopting either package: "Package B has been archived on GitHub", "Package A shipped 4 majors in 12 months — high API churn." Empty array is fine if nothing to flag.

Return ONLY a JSON object matching the schema. No prose, no markdown, no code fences.`;
