import { Injectable } from '@angular/core';
import { CompatibilityReport } from '../models/npm-package.model';

export type CiProvider = 'github' | 'gitlab';

/**
 * Generates a CI pipeline that:
 *   1. creates a branch
 *   2. runs the upgrade (ng update / nx migrate)
 *   3. runs tests
 *   4. opens a PR
 *
 * The generated file is intended to be committed to `.github/workflows/` or
 * the project root for GitLab.
 */
@Injectable({ providedIn: 'root' })
export class CiGeneratorService {
  generate(report: CompatibilityReport, provider: CiProvider): string {
    return provider === 'github' ? this.github(report) : this.gitlab(report);
  }

  filename(provider: CiProvider): string {
    return provider === 'github' ? '.github/workflows/auto-upgrade.yml' : '.gitlab-ci.yml';
  }

  private updateSteps(report: CompatibilityReport): string {
    if (report.nxMigrateCommand) {
      return [
        report.nxMigrateCommand.split('\n').map((l) => `          ${l}`).join('\n')
      ].join('\n');
    }
    const lines: string[] = [];
    if (report.ngUpdateCommand) lines.push(`          ${report.ngUpdateCommand}`);
    if (report.installCommand) lines.push(`          ${report.installCommand}`);
    return lines.join('\n') || `          echo "No upgrade commands generated."`;
  }

  private github(report: CompatibilityReport): string {
    const branch = `chore/angular-${report.targetAngularMajor}-upgrade`;
    return `# Generated by ng-package-compat.
# Trigger manually from the Actions tab; commits the upgrade to a branch and opens a PR.
name: Auto upgrade Angular & dependencies

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Apply upgrade
        run: |
${this.updateSteps(report)}
      - name: Verify build & tests
        run: ${report.verifyCommand || 'npm run build -- --configuration production && npm test -- --watch=false --browsers=ChromeHeadless'}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${branch}
          title: "chore(deps): upgrade to Angular ${report.targetAngularMajor}"
          commit-message: "chore(deps): automated upgrade to Angular ${report.targetAngularMajor}"
          body: |
            This PR was generated by ng-package-compat.
            - Target Angular: ${report.targetAngularMajor}
            - Health score: ${report.health.score}/100 (${report.health.grade})
            - Estimated effort: ${report.estimate.summary}
`;
  }

  private gitlab(report: CompatibilityReport): string {
    return `# Generated by ng-package-compat.
# Manual pipeline that commits the upgrade to a new branch.
stages: [upgrade, verify]

image: node:22

upgrade:
  stage: upgrade
  when: manual
  script:
    - npm ci
${this.updateSteps(report)}
  artifacts:
    paths:
      - package.json
      - package-lock.json

verify:
  stage: verify
  needs: [upgrade]
  script:
    - ${report.verifyCommand || 'npm run build -- --configuration production && npm test -- --watch=false --browsers=ChromeHeadless'}
`;
  }
}
