import { Injectable } from '@angular/core';
import { CompatibilityReport, ReportEntry } from '../models/npm-package.model';

/**
 * Converts a compatibility report into a nicely formatted Markdown document,
 * ready to be pasted into a Jira/GitHub issue.
 *
 * The output uses GitHub-flavoured Markdown: tables, checkbox task list, and
 * fenced code blocks.
 */
@Injectable({ providedIn: 'root' })
export class MarkdownExportService {
  toMarkdown(report: CompatibilityReport): string {
    const lines: string[] = [];
    const title =
      report.mode === 'upgrade'
        ? `Angular upgrade: ${report.currentAngularMajor ?? '?'} → ${report.targetAngularMajor}`
        : `Dependency optimization (Angular ${report.targetAngularMajor})`;

    lines.push(`# ${title}`, '');
    lines.push(
      `**Health score:** ${report.health.score}/100 (${report.health.grade}) · ` +
      `**Estimate:** ${report.estimate.summary}`,
      ''
    );

    lines.push(
      `| ✅ Safe | ⚠️ Warning | 🔥 Breaking | ❓ Unknown | ⛔ License | 🧩 Deprecated |`,
      `| ------: | --------: | ---------: | --------: | --------: | -----------: |`,
      `| ${report.safeCount} | ${report.warningCount} | ${report.conflictCount} | ${report.unknownCount} | ${report.licenseBlockerCount} | ${report.deprecatedCount} |`,
      ''
    );

    if (report.ngUpdateCommand) {
      lines.push('## One-command upgrade', '', '```bash', report.ngUpdateCommand, '```', '');
    }
    if (report.nxMigrateCommand) {
      lines.push('## Nx migration', '', '```bash', report.nxMigrateCommand, '```', '');
    }
    if (report.installCommand) {
      lines.push('## Install remaining packages', '', '```bash', report.installCommand, '```', '');
    }
    if (report.rollbackCommand) {
      lines.push('## Safe rollback', '', '```bash', report.rollbackCommand, '```', '');
    }

    lines.push('## Task checklist', '');
    const priority = [...report.entries].sort(
      (a, b) => this.rank(a) - this.rank(b)
    );
    for (const e of priority) {
      if (e.status === 'safe') continue;
      lines.push(
        `- [ ] **${e.name}** ` +
          `\`${e.currentVersion ?? '—'}\` → \`${this.recommended(e, report.mode)}\` ` +
          `— ${this.statusLabel(e)}` +
          (e.note ? ` · ${e.note}` : '')
      );
      if (e.breakingChanges?.length) {
        for (const bc of e.breakingChanges) {
          lines.push(`  - ⚠️ **${bc.title}** — ${bc.detail}` + (bc.link ? ` ([docs](${bc.link}))` : ''));
        }
      }
      if (e.deprecation?.alternatives?.length) {
        const alts = e.deprecation.alternatives.map((a) => `\`${a.name}\` — ${a.rationale}`).join('; ');
        lines.push(`  - 🧩 Deprecated: ${e.deprecation.reason}`);
        lines.push(`    - Alternatives: ${alts}`);
      }
      if (e.uiFrameworkAlert) {
        lines.push(`  - 🎨 ${e.uiFrameworkAlert.title} — ${e.uiFrameworkAlert.detail}`);
      }
      if (e.licenseRisk && e.licenseRisk.risk !== 'safe') {
        lines.push(`  - ⚖️ License: ${e.licenseRisk.note}`);
      }
      if (e.bundleDelta?.deltaBytes != null) {
        const sign = e.bundleDelta.deltaBytes < 0 ? '-' : '+';
        const kb = Math.abs(e.bundleDelta.deltaBytes / 1024).toFixed(1);
        const pct = e.bundleDelta.deltaPercent?.toFixed(0) ?? '—';
        lines.push(`  - 📦 Bundle: ${sign}${kb} KB gzipped (${pct}%)`);
      }
    }

    if (report.peerConflicts.length) {
      lines.push('', '## Peer-dependency conflicts', '');
      for (const c of report.peerConflicts) {
        lines.push(`- **${c.source}** expects \`${c.target}@${c.expected}\` but you have \`${c.actual}\`. ${c.hint}`);
      }
    }

    if (report.config) {
      const all = [
        ...(report.config.angularJson ?? []).map((x) => ({ file: 'angular.json', ...x })),
        ...(report.config.tsconfig ?? []).map((x) => ({ file: 'tsconfig.json', ...x })),
        ...(report.config.browserslist ?? []).map((x) => ({ file: '.browserslistrc', ...x }))
      ];
      if (all.length) {
        lines.push('', '## Config-file review', '');
        for (const c of all) {
          lines.push(`- **${c.file}** — ${c.level.toUpperCase()}: ${c.message}`);
        }
      }
    }

    if (report.mfe && report.mfe.sharedDeps.length) {
      lines.push('', '## Micro-frontend consistency', '');
      lines.push(`Apps: ${report.mfe.apps.join(', ')}`, '');
      lines.push('| Dep | Versions | Status |', '| --- | --- | --- |');
      for (const d of report.mfe.sharedDeps) {
        const cells = Object.entries(d.versions).map(([app, v]) => `${app}: \`${v}\``).join(', ');
        lines.push(`| \`${d.name}\` | ${cells} | ${d.consistent ? '✅ consistent' : '❌ mismatched'} |`);
      }
    }

    if (report.verifyCommand) {
      lines.push('', '## Verify', '', '```bash', report.verifyCommand, '```');
    }

    lines.push('', '---', '_Generated by [ng-package-compat](https://ng-package-compat.app)._');
    return lines.join('\n');
  }

  private statusLabel(e: ReportEntry): string {
    switch (e.status) {
      case 'warning': return '⚠️ Warning';
      case 'conflict': return '🔥 Breaking';
      case 'unknown': return '❓ Unknown';
      default: return '✅ Safe';
    }
  }

  private rank(e: ReportEntry): number {
    return e.status === 'conflict' ? 0 : e.status === 'warning' ? 1 : e.status === 'unknown' ? 2 : 3;
  }

  private recommended(e: ReportEntry, mode: string): string {
    if (mode === 'same-version') {
      return e.recommendedForCurrent?.version ?? e.recommendedForTarget?.version ?? '—';
    }
    return e.recommendedForTarget?.version ?? '—';
  }
}
