import { Injectable, PLATFORM_ID, inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { CompatibilityReport, ReportEntry } from '../models/npm-package.model';

export interface PdfExportOptions {
  title?: string;
  subtitle?: string;
  projectName?: string;
  targetAngular?: number | null;
  currentAngular?: number | null;
  footer?: string;
  /** Accent color — CSS value. */
  accent?: string;
}

/**
 * One-click branded PDF export for compatibility reports.
 *
 * Design choice: no external library (jsPDF / pdfmake / pdf-lib).
 *
 * Instead, we open a fresh `window` with a purpose-built HTML document and
 * trigger `window.print()`. The browser's native "Save as PDF" dialog produces
 * a high-fidelity, scalable-font PDF that:
 *   - Respects the user's paper size (A4 / Letter)
 *   - Handles pagination + page numbers via @page / page-break-inside
 *   - Uses system fonts (no 400kB embedded font ship)
 *   - Works offline (PWA-safe) and costs us nothing to maintain
 *
 * The rendered PDF is deliberately sales-ready: cover page with health
 * summary, per-row status pills, deprecation callouts, and a clean footer.
 *
 * Why this is better than installing jsPDF:
 *   - jsPDF's unicode support is lossy (no bold + RTL without extra fonts)
 *   - jsPDF ships ~250kB to the client
 *   - The browser's Chromium PDF engine is already perfect at this job
 */
@Injectable({ providedIn: 'root' })
export class PdfExportService {
  private readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

  /** Render a compatibility report as a printable PDF document. */
  exportReport(report: CompatibilityReport, opts: PdfExportOptions = {}): void {
    if (!this.isBrowser) return;

    const html = this.buildHtml(report, opts);
    const win = window.open('', '_blank', 'noopener,noreferrer');
    if (!win) {
      // Popup blocked — fall back to an iframe inside the current page.
      this.printViaIframe(html);
      return;
    }

    win.document.open();
    win.document.write(html);
    win.document.close();

    // Wait for layout + webfonts before kicking print.
    win.addEventListener('load', () => {
      // small timeout so any late async font swaps finish.
      setTimeout(() => {
        win.focus();
        win.print();
      }, 150);
    });
  }

  private printViaIframe(html: string): void {
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);

    const doc = iframe.contentDocument;
    if (!doc) return;
    doc.open();
    doc.write(html);
    doc.close();

    iframe.onload = () => {
      try {
        iframe.contentWindow?.focus();
        iframe.contentWindow?.print();
      } finally {
        setTimeout(() => iframe.remove(), 500);
      }
    };
  }

  private buildHtml(report: CompatibilityReport, opts: PdfExportOptions): string {
    const title = opts.title ?? 'Angular Compatibility Report';
    const subtitle = opts.subtitle ?? 'Generated by ng-package-compat';
    const accent = opts.accent ?? '#6366f1';
    const generatedAt = new Date().toLocaleString();
    const total = report.entries.length;
    const conflict = report.conflictCount;
    const warning = report.warningCount;
    const safe = report.safeCount;
    const healthPct = total ? Math.round((safe / total) * 100) : 0;

    const rowsHtml = report.entries.map((e) => this.renderRow(e)).join('');

    return /* html */ `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)}</title>
  <style>
    @page { size: A4; margin: 18mm 14mm 18mm 14mm; }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
      color: #1a1a1a;
      line-height: 1.45;
      font-size: 10.5pt;
      margin: 0;
    }
    h1, h2, h3 { margin: 0; font-weight: 700; }
    .cover {
      page-break-after: always;
      padding: 40mm 10mm 20mm;
      text-align: center;
    }
    .cover .brand {
      display: inline-block;
      padding: 4px 14px;
      border-radius: 999px;
      background: ${accent};
      color: #fff;
      font-size: 9pt;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      margin-bottom: 20mm;
    }
    .cover h1 { font-size: 30pt; color: ${accent}; margin-bottom: 10mm; }
    .cover .sub { color: #555; font-size: 12pt; margin-bottom: 18mm; }
    .cover .meta { color: #333; font-size: 11pt; margin-top: 20mm; }
    .hero-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 6mm;
      margin: 14mm 0;
    }
    .hero {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 6mm 4mm;
      text-align: center;
      background: #fafafa;
    }
    .hero .n { font-size: 22pt; font-weight: 800; color: ${accent}; }
    .hero .lbl { font-size: 9pt; color: #555; text-transform: uppercase; letter-spacing: 0.08em; }
    .hero.safe .n { color: #0f9d58; }
    .hero.warn .n { color: #f2a100; }
    .hero.bad .n { color: #d93025; }
    section.body { padding: 0 2mm; }
    h2 { font-size: 14pt; color: ${accent}; margin: 8mm 0 3mm; border-bottom: 1px solid #e5e7eb; padding-bottom: 2mm; }
    table { width: 100%; border-collapse: collapse; margin-top: 4mm; }
    th, td { padding: 6px 8px; text-align: left; font-size: 9.5pt; vertical-align: top; }
    th { background: #f3f4f6; font-weight: 700; color: #333; border-bottom: 2px solid #d1d5db; }
    tbody tr { page-break-inside: avoid; }
    tbody tr:nth-child(even) { background: #fcfcfc; }
    td.pkg { font-weight: 700; color: #111; }
    td small { color: #666; }
    .badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 999px;
      font-size: 8pt;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .badge.safe     { background: rgba(15,157,88,0.12); color: #0f9d58; }
    .badge.warning  { background: rgba(242,161,0,0.14); color: #a66c00; }
    .badge.conflict { background: rgba(217,48,37,0.12); color: #d93025; }
    .badge.unknown  { background: #eee; color: #555; }
    .depr { color: #d93025; font-weight: 700; }
    footer {
      position: fixed;
      bottom: 6mm;
      left: 14mm; right: 14mm;
      font-size: 8pt;
      color: #777;
      border-top: 1px solid #e5e7eb;
      padding-top: 2mm;
      display: flex; justify-content: space-between;
    }
    @media print {
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="cover">
    <div class="brand">ng-package-compat</div>
    <h1>${escapeHtml(title)}</h1>
    <div class="sub">${escapeHtml(subtitle)}</div>
    ${opts.projectName ? `<div class="meta"><strong>Project:</strong> ${escapeHtml(opts.projectName)}</div>` : ''}
    ${opts.currentAngular != null ? `<div class="meta"><strong>Current Angular:</strong> ${opts.currentAngular}</div>` : ''}
    ${opts.targetAngular != null ? `<div class="meta"><strong>Target Angular:</strong> ${opts.targetAngular}</div>` : ''}
    <div class="meta" style="margin-top:10mm;">Generated ${escapeHtml(generatedAt)}</div>

    <div class="hero-grid">
      <div class="hero"><div class="n">${total}</div><div class="lbl">Dependencies</div></div>
      <div class="hero bad"><div class="n">${conflict}</div><div class="lbl">Conflicts</div></div>
      <div class="hero warn"><div class="n">${warning}</div><div class="lbl">Warnings</div></div>
      <div class="hero safe"><div class="n">${safe}</div><div class="lbl">Safe</div></div>
    </div>
    <div style="font-size:11pt;color:#333;">Overall health: <strong style="color:${accent};">${healthPct}%</strong></div>
  </div>

  <section class="body">
    <h2>Dependency-by-dependency detail</h2>
    <table>
      <thead>
        <tr>
          <th style="width:28%">Package</th>
          <th style="width:17%">Current</th>
          <th style="width:17%">Recommended</th>
          <th style="width:10%">Status</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        ${rowsHtml || `<tr><td colspan="5"><em>No dependencies were analyzed.</em></td></tr>`}
      </tbody>
    </table>
  </section>

  <footer>
    <span>${escapeHtml(opts.footer ?? 'Confidential — internal use')}</span>
    <span>ng-package-compat • ${escapeHtml(generatedAt)}</span>
  </footer>
</body>
</html>`;
  }

  private renderRow(e: ReportEntry): string {
    const current = e.currentVersion ?? e.currentRange ?? '—';
    const recommended = e.recommendedForTarget?.version ?? '—';
    const badge = e.status;
    const deprecated = e.deprecation?.npmDeprecated
      ? `<div class="depr">Deprecated: ${escapeHtml(e.deprecation.reason ?? 'see npm advisory')}</div>`
      : '';
    const note = e.note ? escapeHtml(e.note) : '';
    return `
      <tr>
        <td class="pkg">${escapeHtml(e.name)}<br/><small>${e.ngUpdateAware ? 'ng update aware' : ''}</small></td>
        <td>${escapeHtml(current)}</td>
        <td>${escapeHtml(recommended)}</td>
        <td><span class="badge ${badge}">${badge}</span></td>
        <td>${deprecated}${note}</td>
      </tr>`;
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
